export enum Role {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  STOCK_MANAGER = 'STOCK_MANAGER',
  CASHIER = 'CASHIER',
  VIEWER = 'VIEWER',
}

export enum StockTransactionType {
  OPENING_STOCK = 'OPENING_STOCK',
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  SALE_RETURN = 'SALE_RETURN',
  PURCHASE_RETURN = 'PURCHASE_RETURN',
  DAMAGE = 'DAMAGE',
  LOST = 'LOST',
  ADJUSTMENT_IN = 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
}

export enum StockOutReason {
  SALE = 'SALE',
  DAMAGE = 'DAMAGE',
  LOST = 'LOST',
  PERSONAL_USE = 'PERSONAL_USE',
  ADJUSTMENT = 'ADJUSTMENT',
  OTHER = 'OTHER',
}

export enum PurchaseStatus {
  DRAFT = 'DRAFT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum SaleStatus {
  DRAFT = 'DRAFT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PAID = 'PAID',
  PARTIAL = 'PARTIAL',
  UNPAID = 'UNPAID',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  BKASH = 'BKASH',
  NAGAD = 'NAGAD',
  CARD = 'CARD',
  OTHER = 'OTHER',
}

export enum PaymentType {
  SALE_PAYMENT = 'SALE_PAYMENT',
  PURCHASE_PAYMENT = 'PURCHASE_PAYMENT',
  CUSTOMER_RECEIPT = 'CUSTOMER_RECEIPT',
  SUPPLIER_PAYMENT = 'SUPPLIER_PAYMENT',
}

export enum NotificationType {
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  PAYMENT_DUE = 'PAYMENT_DUE',
  SYSTEM = 'SYSTEM',
  BACKUP = 'BACKUP',
  OTHER = 'OTHER',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_ARCHIVED = 'PRODUCT_ARCHIVED',
  PRODUCT_RESTORED = 'PRODUCT_RESTORED',
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  PURCHASE_CREATED = 'PURCHASE_CREATED',
  PURCHASE_CANCELLED = 'PURCHASE_CANCELLED',
  PURCHASE_RETURN = 'PURCHASE_RETURN',
  SALE_CREATED = 'SALE_CREATED',
  SALE_CANCELLED = 'SALE_CANCELLED',
  SALE_RETURN = 'SALE_RETURN',
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_DELETED = 'EXPENSE_DELETED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
}
